### PR TITLE
feat(fastrp): remove random udf for faster execution

### PR DESCRIPTION
**Pull request by parkererickson**
### PR Summary
  * FastRP edits that speedup runtime by 14x, remove random udf

### PR Checklist
* [ X] Added comments for more comprehensible code.
* [ ] Added unit and/or regression tests.
* [ ] (Optional) Notified Doc/Prod team, if this PR contains any new features. 

### What is the behavior change?
Removed UDF for faster random initialization.

### CODE REVIEW

**Comment by parkererickson** [comment]
@wyatt-joyner-tg

**Review by wyatt-joyner-tg — APPROVED** [review]
I was around for the development of this, so I approve!

**Comment by YimingPan-Code** [comment]
please use algos repo

**Comment by TannerW** [comment]
I have confirmed that this can be closed with @parkererickson

**Pull request closed without merging**
